trigger:
 branches:
   include:
     - main

pool: manojs

stages:
  - stage: TerraformIPV
    jobs:
      - job: 
        steps:
          - task: TerraformInstaller@1
            displayName: Terraform install
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            displayName: Terraform init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'infrapipeline'
              backendAzureRmStorageAccountName: 'stpunnu'
              backendAzureRmContainerName: 'punnu12'
              backendAzureRmKey: 'terraform.tfstate'
          - task: TerraformTask@5
            displayName: terraform validate
            inputs:
              provider: 'azurerm'
              command: 'validate'
          - task: TerraformTask@5
            displayName: Terraform Plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'infrapipeline'
          - task: TerraformTask@5
            displayName: Terraform Apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'infrapipeline'

